server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: inst-comment-service
  datasource:
    url: jdbc:postgresql://postgres-comment:5432/comment
    #url: jdbc:postgresql://localhost:5432/comment
    username: postgres
    password: 1234
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
