create table comments
(
    comment_id      int8 generated by default as identity,
    comment_created timestamp not null,
    comment_text    varchar(2048),
    post_id         int8      not null,
    user_id         int8      not null,
    primary key (comment_id)
);